# Use node 8.11.3 as the base image
FROM circleci/node:8.11.3

RUN sudo apt-get update \
    && sudo apt-get install lsb-release libappindicator3-1 curl libasound2 libnspr4 libnss3 libxss1 xdg-utils fonts-liberation \
    && sudo curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && sudo dpkg -i google-chrome.deb \
    && sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome \
    && sudo rm google-chrome.deb

RUN google-chrome --version

# set working directory
WORKDIR /usr/src/app

# install dependencies
USER root
COPY ./frontend/package*.json /usr/src/app/
RUN npm install

# add node_modules to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# start app
CMD ng serve --host 0.0.0.0
